# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chirp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chirp

    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'AFOAuth2Manager', '~> 3.0'

  target 'ChirpTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'AFOAuth2Manager', '~> 3.0'
    
  end

end
